-- Supabase schema for Yusr app (content + user sync tables)
-- Run this once in Supabase SQL Editor before seeding.

create extension if not exists pgcrypto;

-- =============================
-- Catalog content tables
-- =============================

create table if not exists public.quran_surahs (
  surah_number integer primary key,
  name_ar text not null,
  name_en text not null,
  verses_count integer not null check (verses_count >= 0),
  created_at timestamptz not null default now()
);

create table if not exists public.quran_verses (
  surah_number integer not null references public.quran_surahs (surah_number) on delete cascade,
  verse_number integer not null,
  text_ar text not null,
  juz_number integer not null,
  page_number integer not null,
  created_at timestamptz not null default now(),
  primary key (surah_number, verse_number)
);

create index if not exists idx_quran_verses_page_number on public.quran_verses (page_number);
create index if not exists idx_quran_verses_juz_number on public.quran_verses (juz_number);

create table if not exists public.adhkar_categories (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  name_ar text not null,
  name_en text,
  sort_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.adhkar_items (
  id bigint generated by default as identity primary key,
  category_id bigint not null references public.adhkar_categories (id) on delete cascade,
  text_ar text not null,
  repeat_count integer not null default 1,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  unique (category_id, sort_order)
);

create index if not exists idx_adhkar_items_category_id on public.adhkar_items (category_id);

create table if not exists public.daily_content (
  content_date date primary key,
  content text not null,
  source text not null,
  theme text,
  created_at timestamptz not null default now()
);

-- =============================
-- User-sync tables
-- =============================

create table if not exists public.user_settings (
  user_id uuid primary key references auth.users (id) on delete cascade,
  lang_code text not null default 'ar',
  prayer_offset integer not null default 0,
  play_adhan boolean not null default true,
  sticky_notification boolean not null default false,
  adhan_sound text not null default 'adhan',
  quran_read_as_text boolean not null default true,
  fasting_reminders_enabled boolean not null default false,
  white_days_reminder_enabled boolean not null default false,
  monday_thursday_reminder_enabled boolean not null default false,
  updated_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create table if not exists public.user_reminders (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  title text not null,
  subtitle text not null,
  frequency text not null check (frequency in ('daily', 'weekly_friday')),
  weekday integer,
  time_of_day time not null,
  enabled boolean not null default true,
  icon_code_point integer not null default 0,
  source_id text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_user_reminders_user_id on public.user_reminders (user_id);

create table if not exists public.user_quran_last_read (
  user_id uuid primary key references auth.users (id) on delete cascade,
  surah_number integer not null,
  verse_number integer not null,
  page_number integer not null,
  juz_number integer not null,
  updated_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create table if not exists public.user_quran_bookmarks (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users (id) on delete cascade,
  surah_number integer not null,
  verse_number integer not null,
  page_number integer not null,
  juz_number integer not null,
  created_at timestamptz not null default now(),
  unique (user_id, surah_number, verse_number, page_number)
);

create index if not exists idx_user_quran_bookmarks_user_id on public.user_quran_bookmarks (user_id);

-- =============================
-- updated_at trigger
-- =============================

create or replace function public.touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_user_settings_updated_at on public.user_settings;
create trigger trg_user_settings_updated_at
before update on public.user_settings
for each row
execute function public.touch_updated_at();

drop trigger if exists trg_user_reminders_updated_at on public.user_reminders;
create trigger trg_user_reminders_updated_at
before update on public.user_reminders
for each row
execute function public.touch_updated_at();

drop trigger if exists trg_user_quran_last_read_updated_at on public.user_quran_last_read;
create trigger trg_user_quran_last_read_updated_at
before update on public.user_quran_last_read
for each row
execute function public.touch_updated_at();

-- =============================
-- RLS policies
-- =============================

alter table public.quran_surahs enable row level security;
alter table public.quran_verses enable row level security;
alter table public.adhkar_categories enable row level security;
alter table public.adhkar_items enable row level security;
alter table public.daily_content enable row level security;

alter table public.user_settings enable row level security;
alter table public.user_reminders enable row level security;
alter table public.user_quran_last_read enable row level security;
alter table public.user_quran_bookmarks enable row level security;

-- Public read for content tables (anon + authenticated)
drop policy if exists quran_surahs_read_all on public.quran_surahs;
create policy quran_surahs_read_all
on public.quran_surahs
for select
to anon, authenticated
using (true);

drop policy if exists quran_verses_read_all on public.quran_verses;
create policy quran_verses_read_all
on public.quran_verses
for select
to anon, authenticated
using (true);

drop policy if exists adhkar_categories_read_all on public.adhkar_categories;
create policy adhkar_categories_read_all
on public.adhkar_categories
for select
to anon, authenticated
using (true);

drop policy if exists adhkar_items_read_all on public.adhkar_items;
create policy adhkar_items_read_all
on public.adhkar_items
for select
to anon, authenticated
using (true);

drop policy if exists daily_content_read_all on public.daily_content;
create policy daily_content_read_all
on public.daily_content
for select
to anon, authenticated
using (true);

-- Per-user access policies for sync tables
drop policy if exists user_settings_owner_all on public.user_settings;
create policy user_settings_owner_all
on public.user_settings
for all
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists user_reminders_owner_all on public.user_reminders;
create policy user_reminders_owner_all
on public.user_reminders
for all
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists user_quran_last_read_owner_all on public.user_quran_last_read;
create policy user_quran_last_read_owner_all
on public.user_quran_last_read
for all
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists user_quran_bookmarks_owner_all on public.user_quran_bookmarks;
create policy user_quran_bookmarks_owner_all
on public.user_quran_bookmarks
for all
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);
