-- Content manifest table for app startup downloads.
-- Execute in Supabase SQL editor.

create table if not exists public.files (
  id bigint generated by default as identity primary key,
  name text not null,
  type text not null check (type in ('quran', 'adhkar')),
  url text not null,
  size bigint not null default 0 check (size >= 0),
  is_active boolean not null default true,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  unique (type, name)
);

create index if not exists idx_files_type_active
  on public.files (type, is_active);

create or replace function public.touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

drop trigger if exists trg_files_touch_updated_at on public.files;
create trigger trg_files_touch_updated_at
before update on public.files
for each row
execute function public.touch_updated_at();

alter table public.files enable row level security;

drop policy if exists "public can read active files" on public.files;
create policy "public can read active files"
on public.files
for select
to anon, authenticated
using (is_active = true);

-- Optional bucket for static content files referenced by URL.
insert into storage.buckets (id, name, public)
values ('app-content', 'app-content', true)
on conflict (id) do nothing;

-- Public read policy for content objects.
drop policy if exists "public read app-content" on storage.objects;
create policy "public read app-content"
on storage.objects
for select
to anon, authenticated
using (bucket_id = 'app-content');

-- Optional: Quran page images manifest for loading images from Supabase.
create table if not exists public.quran_page_images (
  page_number integer primary key check (page_number between 1 and 604),
  url text not null,
  is_active boolean not null default true,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

drop trigger if exists trg_quran_page_images_touch_updated_at on public.quran_page_images;
create trigger trg_quran_page_images_touch_updated_at
before update on public.quran_page_images
for each row
execute function public.touch_updated_at();

alter table public.quran_page_images enable row level security;

drop policy if exists "public can read active quran page images" on public.quran_page_images;
create policy "public can read active quran page images"
on public.quran_page_images
for select
to anon, authenticated
using (is_active = true);

-- Helper seed (edit YOUR_PROJECT_REF then run once):
-- insert into public.quran_page_images (page_number, url, is_active)
-- select
--   page,
--   format(
--     'https://%s.supabase.co/storage/v1/object/public/app-content/quran_images/%s.png',
--     'YOUR_PROJECT_REF',
--     page
--   ),
--   true
-- from generate_series(1, 604) as page
-- on conflict (page_number)
-- do update set
--   url = excluded.url,
--   is_active = excluded.is_active,
--   updated_at = timezone('utc', now());

-- No-assets mode helpers (Quran fully from downloaded/remote content, no local assets):
-- 1) Register Quran catalog JSON from storage path app-content/quran/mainDataQuran.json
--    (run after uploading the file)
-- insert into public.files (name, type, url, size, is_active)
-- values (
--   'mainDataQuran.json',
--   'quran',
--   'https://rkpjvaibupjagdpsfnnz.supabase.co/storage/v1/object/public/app-content/quran/mainDataQuran.json',
--   0,
--   true
-- )
-- on conflict (type, name)
-- do update set
--   url = excluded.url,
--   size = excluded.size,
--   is_active = excluded.is_active,
--   updated_at = timezone('utc', now());

-- 2) Register Quran page images from storage folder app-content/quran_images/
--    (it uses storage object metadata size automatically)
-- insert into public.files (name, type, url, size, is_active)
-- select
--   regexp_replace(o.name, '^.*/', '') as name,
--   'quran' as type,
--   format(
--     'https://rkpjvaibupjagdpsfnnz.supabase.co/storage/v1/object/public/app-content/%s',
--     o.name
--   ) as url,
--   coalesce((o.metadata ->> 'size')::bigint, 0) as size,
--   true as is_active
-- from storage.objects o
-- where o.bucket_id = 'app-content'
--   and o.name like 'quran_images/%'
-- on conflict (type, name)
-- do update set
--   url = excluded.url,
--   size = excluded.size,
--   is_active = excluded.is_active,
--   updated_at = timezone('utc', now());
